"""create_projects_table

Revision ID: dba9bff1e2a4
Revises: 12025802ab71
Create Date: 2026-07-06 11:17:33.070299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.enums import ProjectStatus


# revision identifiers, used by Alembic.
revision: str = 'dba9bff1e2a4'
down_revision: Union[str, Sequence[str], None] = '12025802ab71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum("ACTIVE", "INACTIVE", "DELETED", name="projectstatus"), server_default=sa.text("'ACTIVE'::projectstatus"), type_=sa.Enum(ProjectStatus), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_uuid'), 'projects', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_uuid'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
